services:
    db:
        image: mysql
        # command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        volumes:
            - db-data-1:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db

    web:
        build: Docker
        restart: on-failure
        volumes:
            - ./app:/app:rw
        ports:
            - 8000:80

volumes:
    db-data-1: null
